# Generated by Django 3.0.5 on 2021-02-14 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0003_arquivo_processado'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='dataHoraCriacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Captura automaticamente a data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arquivo',
            name='dataHoraFimProcessamento',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Instante de início de execução da Tarefa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arquivo',
            name='dataHoraInicioProcessamento',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Instante de início de execução da Tarefa'),
            preserve_default=False,
        ),
    ]
