# Generated by Django 3.0.5 on 2021-02-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0004_auto_20210214_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraFimProcessamento',
            field=models.DateTimeField(blank=True, help_text='Instante de início de execução da Tarefa', null=True),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraInicioProcessamento',
            field=models.DateTimeField(blank=True, help_text='Instante de início de execução da Tarefa', null=True),
        ),
    ]
