# Generated by Django 3.0.5 on 2021-02-14 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0005_auto_20210214_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraCriacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 12, 23, 44, 600921), help_text='Captura automaticamente a data de criação'),
        ),
    ]
