# Generated by Django 3.0.5 on 2021-02-14 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0006_auto_20210214_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraCriacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 12, 24, 17, 249100), help_text='Captura automaticamente a data de criação'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraFimProcessamento',
            field=models.DateTimeField(blank=True, default=None, help_text='Instante de início de execução da Tarefa', null=True),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraInicioProcessamento',
            field=models.DateTimeField(blank=True, default=None, help_text='Instante de início de execução da Tarefa', null=True),
        ),
    ]
