# Generated by Django 3.0.5 on 2021-02-15 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0007_auto_20210214_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='tempoExecucaoSegundos',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraCriacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 12, 24, 22, 320566), help_text='Captura automaticamente a data de criação'),
        ),
    ]
