# Generated by Django 3.0.5 on 2021-02-15 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0008_auto_20210215_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraCriacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 12, 27, 4, 132540), help_text='Captura automaticamente a data de criação'),
        ),
    ]
