# Generated by Django 3.0.5 on 2021-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0009_auto_20210215_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraCriacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de criação'),
        ),
    ]
