# Generated by Django 3.0.5 on 2021-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0010_auto_20210215_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='resultado_processamento',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
