# Generated by Django 3.0.5 on 2021-02-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0011_arquivo_resultado_processamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='csv_processado',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documentos', verbose_name='Anexe o documento'),
        ),
    ]
