# Generated by Django 3.0.5 on 2021-02-15 23:18

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0012_arquivo_csv_processado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='csv_processado',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='resultado_dataFrame',
            field=picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True),
        ),
    ]
