# Generated by Django 3.0.5 on 2021-02-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0013_auto_20210215_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='resultado_dataFrame',
        ),
    ]
