# Generated by Django 3.0.5 on 2021-02-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0014_remove_arquivo_resultado_dataframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='forma_envio',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Forma de envio'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraCriacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Instante de envio do arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='dataHoraFimProcessamento',
            field=models.DateTimeField(blank=True, default=None, help_text='Instante de fim de execução da Tarefa', null=True),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='processado',
            field=models.BooleanField(default=False, verbose_name='Processado (marcado se Verdadeiro)'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='resultado_processamento',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Resultado do processamento'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tempoExecucaoSegundos',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Tempo de execução em segundos'),
        ),
    ]
