# Generated by Django 3.0.5 on 2021-02-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0017_arquivo_id_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='ultimo_evento',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='task_context',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contexto da task'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='id_task',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Task'),
        ),
    ]
